### ISSUE TITLE
Add CI before the next release

### ISSUE THREAD

**Issue by mjambon** [dmbaturin/ocaml-tsort#4]
I'd like to set up CircleCI before making a release. It's free for open-source projects and would give us a guarantee that a release will work for a desired range of OCaml versions.

It requires the github project owner to:
1. Create a CircleCI account
2. Add the project from the CircleCI dashboard
3. Add me as a contributor on the CircleCI project so I can set things up

The setup will consist in adding a `.circleci` folder to the github project, which CircleCI will use to build the project with every commit and notify us if something fails. See https://github.com/mjambon/dune-deps/tree/master/.circleci for an example.

**Comment by mjambon** [comment]
Note that this week is about to be very busy for me. Hopefully I can get back to this over the coming weekend.

**Comment by dmbaturin** [comment]
I agree, generally. I have Travis enabled in some of my projects, and it fails for stupid reasons all too often (like the build VM unable resolve domain names).
Also, OCaml builds are painfully slow because Travis doesn't support OCaml (while supporting Perl6), and I'm having to compile the whole toolchain every time.

I haven't tried CircleCI yet, but if it's more reliable and easier to use with OCaml, I'm all for it.

**Comment by mjambon** [comment]
I haven't used Travis directly, so I'm not sure about it. With CircleCI, we'd pull a docker image that has a lot of the opam stuff preinstalled so it doesn't take long to build and test a simple code base. However the config is a yaml file, not a plain dockerfile, and there's no automatic caching of the different steps like when running docker on a single host. I think they offer a way to cache certain things explicitly, but I'm confident we won't need that.

**Comment by dmbaturin** [comment]
Since the CI has been running fine for a long time, I guess this is a solved issue. :)
